rdb.fields = {
	{"enhance_id", TYPE_INT32},
	{"enhance_type", TYPE_INT8},
	{"fail_result", TYPE_INT8},
	{"max_enhance", TYPE_INT8},
	{"local_flag", TYPE_INT32},
	{"need_item", TYPE_INT32},
	{"percentage_1", TYPE_FLOAT32},
	{"percentage_2", TYPE_FLOAT32},
	{"percentage_3", TYPE_FLOAT32},
	{"percentage_4", TYPE_FLOAT32},
	{"percentage_5", TYPE_FLOAT32},
	{"percentage_6", TYPE_FLOAT32},
	{"percentage_7", TYPE_FLOAT32},
	{"percentage_8", TYPE_FLOAT32},
	{"percentage_9", TYPE_FLOAT32},
	{"percentage_10", TYPE_FLOAT32},
	{"percentage_11", TYPE_FLOAT32},
	{"percentage_12", TYPE_FLOAT32},
	{"percentage_13", TYPE_FLOAT32},
	{"percentage_14", TYPE_FLOAT32},
	{"percentage_15", TYPE_FLOAT32},
	{"percentage_16", TYPE_FLOAT32},
	{"percentage_17", TYPE_FLOAT32},
	{"percentage_18", TYPE_FLOAT32},
	{"percentage_19", TYPE_FLOAT32},
	{"percentage_20", TYPE_FLOAT32},
}

