rdb.fields = {
	{"id", TYPE_INT32},
	{"name_id", TYPE_INT32},
	{"type", TYPE_INT32},
	{"group", TYPE_INT32},
	{"class", TYPE_INT32},
	{"rank", TYPE_INT32},
	{"use_min_level", TYPE_INT32},
	{"use_max_level", TYPE_INT32},
	{"target_min_level", TYPE_INT32},
	{"target_max_level", TYPE_INT32},
	{"range", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"weight", TYPE_INT32},
	{"price", TYPE_INT32},
	{"endurance", TYPE_INT32},
	{"wear_type", TYPE_INT32},
	{"nv0", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv1", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"limit_deva", TYPE_BIT},
	{"limit_asura", TYPE_BIT},
	{"limit_gaia", TYPE_BIT},
	{"nv2", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv3", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv4", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv5", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv6", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"limit_fighter", TYPE_BIT},
	{"limit_hunter", TYPE_BIT},
	{"limit_magician", TYPE_BIT},
	{"limit_summoner", TYPE_BIT},
	{"nv7", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv8", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv9", TYPE_INT16 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"flag_cashitem", TYPE_BIT},
	{"flag_wear", TYPE_BIT},
	{"flag_storage", TYPE_BIT},
	{"flag_enhance", TYPE_BIT},
	{"flag_use", TYPE_BIT},
	{"nv10", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv11", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"flag_duplicate", TYPE_BIT},
	{"flag_target_use", TYPE_BIT},
	{"nv12", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"flag_trade", TYPE_BIT},
	{"flag_sell", TYPE_BIT},
	{"flag_quest", TYPE_BIT},
	{"flag_overweight", TYPE_BIT},
	{"flag_riding", TYPE_BIT},
	{"flag_drop", TYPE_BIT},
	{"flag_move", TYPE_BIT},
	{"flag_sit", TYPE_BIT},
	{"flag_raid", TYPE_BIT},
	{"flag_secroute", TYPE_BIT},
	{"flag_eventmap", TYPE_BIT},
	{"flag_huntaholic", TYPE_BIT},
	{"nv13", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv14", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"nv15", TYPE_INT8 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"material", TYPE_INT32},
	{"summon_id", TYPE_INT32},
	{"throw_range", TYPE_INT32},
	{"base_type_0", TYPE_INT16},
	{"base_type_1", TYPE_INT16},
	{"base_type_2", TYPE_INT16},
	{"base_type_3", TYPE_INT16},
	{"base_var1_0", TYPE_FLOAT64},
	{"base_var1_1", TYPE_FLOAT64},
	{"base_var1_2", TYPE_FLOAT64},
	{"base_var1_3", TYPE_FLOAT64},
	{"base_var2_0", TYPE_FLOAT64},
	{"base_var2_1", TYPE_FLOAT64},
	{"base_var2_2", TYPE_FLOAT64},
	{"base_var2_3", TYPE_FLOAT64},
	{"opt_type_0", TYPE_INT16},
	{"opt_type_1", TYPE_INT16},
	{"opt_type_2", TYPE_INT16},
	{"opt_type_3", TYPE_INT16},
	{"opt_var1_0", TYPE_FLOAT64},
	{"opt_var1_1", TYPE_FLOAT64},
	{"opt_var1_2", TYPE_FLOAT64},
	{"opt_var1_3", TYPE_FLOAT64},
	{"opt_var2_0", TYPE_FLOAT64},
	{"opt_var2_1", TYPE_FLOAT64},
	{"opt_var2_2", TYPE_FLOAT64},
	{"opt_var2_3", TYPE_FLOAT64},
	{"enhance_0_id", TYPE_INT16},
	{"enhance_1_id", TYPE_INT16},
	{"enhance_0_01", TYPE_FLOAT32},
	{"enhance_0_02", TYPE_FLOAT32},
	{"enhance_0_03", TYPE_FLOAT32},
	{"enhance_0_04", TYPE_FLOAT32},
	{"enhance_1_01", TYPE_FLOAT32},
	{"enhance_1_02", TYPE_FLOAT32},
	{"enhance_1_03", TYPE_FLOAT32},
	{"enhance_1_04", TYPE_FLOAT32},
	{"skill_id", TYPE_INT32},
	{"state_id", TYPE_INT32},
	{"state_level", TYPE_INT32},
	{"state_time", TYPE_INT32},
	{"state_type?", TYPE_INT8},
	{"cool_time", TYPE_INT32},
	{"cool_time_group", TYPE_INT16},
	{"available_period", TYPE_INT32},
	{"decrease_type", TYPE_INT8},
	{"model_type_dem", TYPE_INT32},
	{"model_type_def", TYPE_INT32},
	{"model_type_asm", TYPE_INT32},
	{"model_type_asf", TYPE_INT32},
	{"model_type_gam", TYPE_INT32},
	{"model_type_gaf", TYPE_INT32},
	{"model_00", TYPE_CHAR, 256},
	{"model_01", TYPE_CHAR, 256},
	{"model_02", TYPE_CHAR, 256},
	{"model_03", TYPE_CHAR, 256},
	{"model_04", TYPE_CHAR, 256},
	{"model_05", TYPE_CHAR, 256},
	{"model_06", TYPE_CHAR, 256},
	{"model_07", TYPE_CHAR, 256},
	{"model_08", TYPE_CHAR, 256},
	{"model_09", TYPE_CHAR, 256},
	{"model_10", TYPE_CHAR, 256},
	{"model_11", TYPE_CHAR, 256},
	{"model_12", TYPE_CHAR, 256},
	{"model_13", TYPE_CHAR, 256},
	{"model_14", TYPE_CHAR, 256},
	{"model_15", TYPE_CHAR, 256},
	{"model_16", TYPE_CHAR, 256},
	{"model_17", TYPE_CHAR, 256},
	{"drop_type", TYPE_CHAR, 256},
	{"icon_id", TYPE_INT32},
	{"icon_file_name", TYPE_CHAR, 256},
	{"script_text", TYPE_CHAR, 512},
	{"tooltip_id", TYPE_INT32},
}

