rdb.fields = {
	{"id", TYPE_INT32},
	{"texture_change_time", TYPE_INT32},
	{"a", TYPE_INT32},
	{"r", TYPE_INT32},
	{"g", TYPE_INT32},
	{"b", TYPE_INT32},
	{"texture_name_1", TYPE_CHAR, 256},
	{"texture_name_2", TYPE_CHAR, 256},
	{"texture_name_3", TYPE_CHAR, 256},
	{"texture_name_4", TYPE_CHAR, 256},
	{"texture_name_5", TYPE_CHAR, 256},
	{"texture_name_6", TYPE_CHAR, 256},
	{"texture_name_7", TYPE_CHAR, 256},
	{"texture_name_8", TYPE_CHAR, 256},
	{"texture_name_9", TYPE_CHAR, 256},
	{"texture_name_10", TYPE_CHAR, 256},
	{"texture_name_11", TYPE_CHAR, 256},
	{"texture_name_12", TYPE_CHAR, 256},
	{"texture_name_13", TYPE_CHAR, 256},
	{"texture_name_14", TYPE_CHAR, 256},
	{"texture_name_15", TYPE_CHAR, 256},
	{"texture_name_16", TYPE_CHAR, 256},
	{"texture_name_17", TYPE_CHAR, 256},
	{"texture_name_18", TYPE_CHAR, 256},
	{"texture_name_19", TYPE_CHAR, 256},
	{"texture_name_20", TYPE_CHAR, 256},
	{"texture_name_21", TYPE_CHAR, 256},
	{"texture_name_22", TYPE_CHAR, 256},
	{"texture_name_23", TYPE_CHAR, 256},
	{"texture_name_24", TYPE_CHAR, 256},
	{"texture_name_25", TYPE_CHAR, 256},
	{"texture_name_26", TYPE_CHAR, 256},
	{"texture_name_27", TYPE_CHAR, 256},
	{"texture_name_28", TYPE_CHAR, 256},
	{"texture_name_29", TYPE_CHAR, 256},
	{"texture_name_30", TYPE_CHAR, 256},
	{"texture_unknown_1", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_2", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_3", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_4", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_5", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_6", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_7", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_8", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_9", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_10", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_11", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_12", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_13", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_14", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_15", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_16", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_17", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_18", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_19", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_20", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_21", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_22", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_23", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_24", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_25", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_26", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_27", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_28", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_29", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
	{"texture_unknown_30", TYPE_INT32 | TYPE_SQLIGNORE | TYPE_CSVIGNORE | TYPE_GUIIGNORE},
}

rdb.defaultTableName = "LowQualityWater"

rdb.convertData = function (dst, mode, row, rowNum)
	if mode == DCT_Write and dst == DF_RDB then
		for i = 1,30 do
			row["texture_unknown_" .. i] = 0
		end
	end
end
