rdb.fields = {
	{"character_id", TYPE_INT32},
	{"def", TYPE_INT32},
	{"battle", TYPE_INT32},
	{"idle", TYPE_INT32},
	{"walk", TYPE_INT32},
	{"run", TYPE_INT32},
	{"be_attack", TYPE_INT32},
	{"be_attack2", TYPE_INT32},
	{"dead", TYPE_INT32},
	{"flying_dead", TYPE_INT32},
	{"take", TYPE_INT32},
	{"attack_1", TYPE_INT32},
	{"attack_2", TYPE_INT32},
	{"attack_3", TYPE_INT32},
	{"draw_bow", TYPE_INT32},
	{"target_bow", TYPE_INT32},
	{"fire_bow", TYPE_INT32},
	{"casting_1", TYPE_INT32},
	{"casting_2", TYPE_INT32},
	{"casting_3", TYPE_INT32},
	{"melee_1", TYPE_INT32},
	{"melee_2", TYPE_INT32},
	{"melee_3", TYPE_INT32},
	{"mount", TYPE_INT32},
	{"unmount", TYPE_INT32},
}

rdb.defaultTableName = "MonsterMotionSet"

