rdb.fields = {
	{"id", TYPE_INT32},
	{"text_id", TYPE_INT32},
	{"name_text_id", TYPE_INT32},
	{"race_id", TYPE_INT32},
	{"sexsual_id", TYPE_INT32},
	{"x", TYPE_INT32},
	{"y", TYPE_INT32},
	{"z", TYPE_INT32},
	{"face", TYPE_INT32},
	{"local_flag", TYPE_INT32},
	{"face_x", TYPE_INT32},
	{"face_y", TYPE_INT32},
	{"face_z", TYPE_INT32},
	{"model_file", TYPE_CHAR, 256},
	{"hair_id", TYPE_INT32},
	{"face_id", TYPE_INT32},
	{"body_id", TYPE_INT32},
	{"weapon_item_id", TYPE_INT32},
	{"shield_item_id", TYPE_INT32},
	{"clothes_item_id", TYPE_INT32},
	{"helm_item_id", TYPE_INT32},
	{"gloves_item_id", TYPE_INT32},
	{"boots_item_id", TYPE_INT32},
	{"belt_item_id", TYPE_INT32},
	{"mantle_item_id", TYPE_INT32},
	{"necklace_item_id", TYPE_INT32},
	{"earring_item_id", TYPE_INT32},
	{"ring1_item_id", TYPE_INT32},
	{"ring2_item_id", TYPE_INT32},
	{"motion_id", TYPE_INT32},
	{"is_roam", TYPE_INT32},
	{"roaming_id", TYPE_INT32},
	{"standard_walk_speed", TYPE_INT32},
	{"standard_run_speed", TYPE_INT32},
	{"walk_speed", TYPE_INT32},
	{"run_speed", TYPE_INT32},
	{"attackable", TYPE_INT32},
	{"offensive_type", TYPE_INT32},
	{"spawn_type", TYPE_INT32},
	{"chase_range", TYPE_INT32},
	{"regen_time", TYPE_INT32},
	{"level", TYPE_INT32},
	{"stat_id", TYPE_INT32},
	{"attack_range", TYPE_INT32},
	{"attack_speed_type", TYPE_INT32},
	{"hp", TYPE_INT32},
	{"mp", TYPE_INT32},
	{"attack_point", TYPE_INT32},
	{"magic_point", TYPE_INT32},
	{"defence", TYPE_INT32},
	{"magic_defence", TYPE_INT32},
	{"attack_speed", TYPE_INT32},
	{"magic_speed", TYPE_INT32},
	{"accuracy", TYPE_INT32},
	{"avoid", TYPE_INT32},
	{"magic_accuracy", TYPE_INT32},
	{"magic_avoid", TYPE_INT32},
	{"ai_script", TYPE_CHAR, 256},
	{"contact_script", TYPE_CHAR, 256},
	{"texture_group", TYPE_INT32},
	{"type", TYPE_INT8},
}

rdb.defaultFileName = "db_npcresource"

