rdb.fields = {
	{"id", TYPE_INT32},
	{"species_id", TYPE_INT32},
	{"type", TYPE_INT32},
	{"affiliation", TYPE_INT32},
	{"name_id", TYPE_INT32},
	{"cage_id", TYPE_INT32},
	{"skill_tree_id", TYPE_INT32},
	{"attribute_flag", TYPE_INT32},
	{"size", TYPE_FLOAT32},
	{"scale", TYPE_FLOAT32},
	{"target_fx_size", TYPE_FLOAT32},
	{"walk_type", TYPE_INT32},
	{"slant_type", TYPE_INT32},
	{"camera_x", TYPE_INT32},
	{"camera_y", TYPE_INT32},
	{"camera_z", TYPE_INT32},
	{"target_x", TYPE_FLOAT32},
	{"target_y", TYPE_FLOAT32},
	{"target_z", TYPE_FLOAT32},
	{"model", TYPE_CHAR, 256},
	{"motion_file_id", TYPE_INT32},
	{"texture_group", TYPE_INT32},
	{"local_flag", TYPE_INT32},
}

