rdb.fields = {
	{"id", TYPE_INT32},
	{"text_id_quest", TYPE_INT32},
	{"text_id_summary", TYPE_INT32},
	{"text_id_status", TYPE_INT32},
	{"limit_begin_time", TYPE_INT32},
	{"limit_end_time", TYPE_INT32},
	{"limit_level", TYPE_INT32},
	{"limit_job_level", TYPE_INT32},
	{"limit_max_level", TYPE_INT32},
	{"limit_max_job_level", TYPE_INT32},
	{"nv", TYPE_BIT | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"limit_deva", TYPE_BIT},
	{"limit_asura", TYPE_BIT},
	{"limit_gaia", TYPE_BIT},
	{"limit_fighter", TYPE_BIT},
	{"limit_hunter", TYPE_BIT},
	{"limit_magician", TYPE_BIT},
	{"limit_summoner", TYPE_BIT},
	{"padding0", TYPE_INT8 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"padding1", TYPE_INT16 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"limit_job", TYPE_INT32},
	{"limit_favor_group_id", TYPE_INT32 | TYPE_RDBIGNORE},
	{"limit_favor", TYPE_INT32},
	{"repeatable", TYPE_INT8},
	{"unknown1", TYPE_INT8 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"unknown2", TYPE_INT16 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"invoke_condition", TYPE_INT32},
	{"invoke_value", TYPE_INT32},
	{"time_limit_type", TYPE_INT16},
	{"job_depth", TYPE_INT16},
	{"time_limit", TYPE_INT32},
	{"type", TYPE_INT32},
	{"value1", TYPE_INT32},
	{"value2", TYPE_INT32},
	{"value3", TYPE_INT32},
	{"value4", TYPE_INT32},
	{"value5", TYPE_INT32},
	{"value6", TYPE_INT32},
	{"value7", TYPE_INT32},
	{"value8", TYPE_INT32},
	{"value9", TYPE_INT32},
	{"value10", TYPE_INT32},
	{"value11", TYPE_INT32},
	{"value12", TYPE_INT32},
	{"drop_group_id", TYPE_INT32},
	{"quest_difficulty", TYPE_INT32},
	{"favor_group_id", TYPE_INT32 | TYPE_RDBIGNORE},
	{"hate_group_id", TYPE_INT32 | TYPE_RDBIGNORE},
	{"favor", TYPE_INT32},
	{"exp", TYPE_INT32},
	{"jp", TYPE_INT32},
	{"holicpoint", TYPE_INT32},
	{"gold", TYPE_INT32},
	{"default_reward_id", TYPE_INT32},
	{"default_reward_level", TYPE_INT32},
	{"default_reward_quantity", TYPE_INT32},
	{"optional_reward_id1", TYPE_INT32},
	{"optional_reward_level1", TYPE_INT32},
	{"optional_reward_quantity1", TYPE_INT32},
	{"optional_reward_id2", TYPE_INT32},
	{"optional_reward_level2", TYPE_INT32},
	{"optional_reward_quantity2", TYPE_INT32},
	{"optional_reward_id3", TYPE_INT32},
	{"optional_reward_level3", TYPE_INT32},
	{"optional_reward_quantity3", TYPE_INT32},
	{"optional_reward_id4", TYPE_INT32},
	{"optional_reward_level4", TYPE_INT32},
	{"optional_reward_quantity4", TYPE_INT32},
	{"optional_reward_id5", TYPE_INT32},
	{"optional_reward_level5", TYPE_INT32},
	{"optional_reward_quantity5", TYPE_INT32},
	{"optional_reward_id6", TYPE_INT32},
	{"optional_reward_level6", TYPE_INT32},
	{"optional_reward_quantity6", TYPE_INT32},
	{"forequest1", TYPE_INT32},
	{"forequest2", TYPE_INT32},
	{"forequest3", TYPE_INT32},
	{"or_flag", TYPE_INT8},
	{"script_start_text", TYPE_CHAR | TYPE_RDBIGNORE, 512},
	{"script_end_text", TYPE_CHAR | TYPE_RDBIGNORE, 512},
	{"script_drop_text", TYPE_CHAR | TYPE_RDBIGNORE, 512},
	{"unknown4", TYPE_INT8 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"show_target_type", TYPE_INT8},
	{"unknownPadding", TYPE_INT8 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"show_target_id", TYPE_INT32},
	{"mark_hide", TYPE_INT8},
	{"unknown5", TYPE_INT8 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"unknown6", TYPE_INT16 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"cool_time", TYPE_INT32},
	{"accept_cool_time", TYPE_INT32},
}

rdb.sqlColumnOrder = table.concat({
	"id\0",
	"text_id_quest\0",
	"text_id_summary\0",
	"text_id_status\0",
	"limit_begin_time\0",
	"limit_end_time\0",
	"limit_level\0",
	"limit_job_level\0",
	"limit_max_level\0",
	"limit_max_job_level\0",
	"limit_deva\0",
	"limit_asura\0",
	"limit_gaia\0",
	"limit_fighter\0",
	"limit_hunter\0",
	"limit_magician\0",
	"limit_summoner\0",
	"limit_job\0",
	"job_depth\0",
	"limit_favor_group_id\0",
	"limit_favor\0",
	"repeatable\0",
	"invoke_condition\0",
	"invoke_value\0",
	"time_limit_type\0",
	"time_limit\0",
	"type\0",
	"value1\0",
	"value2\0",
	"value3\0",
	"value4\0",
	"value5\0",
	"value6\0",
	"value7\0",
	"value8\0",
	"value9\0",
	"value10\0",
	"value11\0",
	"value12\0",
	"drop_group_id\0",
	"quest_difficulty\0",
	"favor_group_id\0",
	"hate_group_id\0",
	"favor\0",
	"exp\0",
	"jp\0",
	"holicpoint\0",
	"gold\0",
	"default_reward_id\0",
	"default_reward_level\0",
	"default_reward_quantity\0",
	"optional_reward_id1\0",
	"optional_reward_level1\0",
	"optional_reward_quantity1\0",
	"optional_reward_id2\0",
	"optional_reward_level2\0",
	"optional_reward_quantity2\0",
	"optional_reward_id3\0",
	"optional_reward_level3\0",
	"optional_reward_quantity3\0",
	"optional_reward_id4\0",
	"optional_reward_level4\0",
	"optional_reward_quantity4\0",
	"optional_reward_id5\0",
	"optional_reward_level5\0",
	"optional_reward_quantity5\0",
	"optional_reward_id6\0",
	"optional_reward_level6\0",
	"optional_reward_quantity6\0",
	"forequest1\0",
	"forequest2\0",
	"forequest3\0",
	"or_flag\0",
	"script_start_text\0",
	"script_end_text\0",
	"script_drop_text\0",
	"show_target_type\0",
	"show_target_id\0",
	"mark_hide\0",
	"cool_time\0",
	"accept_cool_time\0",
})

rdb.convertData = function (dst, mode, row, rowNum)
	if mode == DCT_Read and (dst == DF_SQL or dst == DF_CSV) then
		row.nv = 0
		row.padding0 = 0
		row.padding1 = 0
		row.unknown1 = 0
		row.unknown2 = 0
		row.unknown4 = 55
		row.unknown5 = 0
		row.unknown6 = 0
		row.unknownPadding = 0
	elseif mode == DCT_Read and dst == DF_RDB then
		local id = row.id;

		if id >= 3600 and id <= 3611 and id ~= 3610 then
			row.hate_group_id = 1
		else
			row.hate_group_id = 0
		end

		row.limit_favor_group_id = 0
		row.favor_group_id = 999
		row.or_flag = row.or_flag * -1

		row.script_start_text = "0"
		row.script_end_text = "0"
		row.script_drop_text = "0"
	end
end
