-- this description might not work on every RDB.
-- See https://www.elitepvpers.com/forum/rappelz-private-server/2769975-release-rappelz-rdb-tool-tabs-21.html#post36807115

rdb.fields = {
	{"id", TYPE_INT32},
	{"text_id", TYPE_INT32},
	{"desc_id", TYPE_INT32 | TYPE_RDBIGNORE},
	{"is_valid", TYPE_INT8},
	{"elemental", TYPE_INT8},
	{"is_passive", TYPE_INT8},
	{"is_physical_act", TYPE_INT8},
	{"is_harmful", TYPE_INT8},
	{"is_need_target", TYPE_INT8},
	{"is_corpse", TYPE_INT8},
	{"is_toggle", TYPE_INT8},
	{"casting_type", TYPE_INT8},
	{"casting_level", TYPE_INT8},
	{"unknown", TYPE_INT16},
	{"toggle_group", TYPE_INT32},
	{"cast_range", TYPE_INT32},
	{"valid_range", TYPE_INT32},
	{"cost_hp", TYPE_INT32},
	{"cost_hp_per_skl", TYPE_INT32},
	{"cost_mp", TYPE_INT32},
	{"cost_mp_per_skl", TYPE_INT32},
	{"cost_mp_per_enhance", TYPE_INT32},
	{"cost_hp_per", TYPE_FLOAT32},
	{"cost_hp_per_skl_per", TYPE_FLOAT32},
	{"cost_mp_per", TYPE_FLOAT32},
	{"cost_mp_per_skl_per", TYPE_FLOAT32},
	{"cost_havoc", TYPE_INT32},
	{"cost_havoc_per_skl", TYPE_INT32},
	{"cost_energy", TYPE_INT32},
	{"cost_energy_per_skl", TYPE_INT32},
	{"cost_exp", TYPE_INT32},
	{"cost_exp_per_enhance", TYPE_INT32},
	{"cost_jp", TYPE_INT32},
	{"cost_jp_per_enhance", TYPE_INT32},
	{"cost_item", TYPE_INT32},
	{"cost_item_count", TYPE_INT32},
	{"cost_item_count_per_skl", TYPE_INT32},
	{"need_level", TYPE_INT32},
	{"need_hp", TYPE_INT32},
	{"need_mp", TYPE_INT32},
	{"need_havoc", TYPE_INT32},
	{"need_havoc_burst", TYPE_INT32},
	{"need_state_id", TYPE_INT32},
	{"need_state_level", TYPE_INT8},
	{"need_state_exhaust", TYPE_INT8},
	{"vf_one_hand_sword", TYPE_INT8},
	{"vf_two_hand_sword", TYPE_INT8},
	{"vf_double_sword", TYPE_INT8},
	{"vf_dagger", TYPE_INT8},
	{"vf_double_dagger", TYPE_INT8},
	{"vf_spear", TYPE_INT8},
	{"vf_axe", TYPE_INT8},
	{"vf_one_hand_axe", TYPE_INT8},
	{"vf_double_axe", TYPE_INT8},
	{"vf_one_hand_mace", TYPE_INT8},
	{"vf_two_hand_mace", TYPE_INT8},
	{"vf_lightbow", TYPE_INT8},
	{"vf_heavybow", TYPE_INT8},
	{"vf_crossbow", TYPE_INT8},
	{"vf_one_hand_staff", TYPE_INT8},
	{"vf_two_hand_staff", TYPE_INT8},
	{"vf_shield_only", TYPE_INT8},
	{"vf_is_not_need_weapon", TYPE_INT8},
	{"delay_cast", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"delay_cast_per_skl", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"delay_cast_mode_per_enhance", TYPE_FLOAT32},
	{"delay_common", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"delay_cooltime", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"delay_cooltime_mode_per_enhance", TYPE_FLOAT32},
	{"cool_time_group_id", TYPE_INT32},
	{"uf_self", TYPE_INT8},
	{"uf_party", TYPE_INT8},
	{"uf_guild", TYPE_INT8},
	{"uf_neutral", TYPE_INT8},
	{"uf_purple", TYPE_INT8},
	{"uf_enemy", TYPE_INT8},
	{"tf_avatar", TYPE_INT8},
	{"tf_summon", TYPE_INT8},
	{"tf_monster", TYPE_INT8},
	{"unknown2", TYPE_INT8},
	{"target", TYPE_INT16},
	{"effect_type", TYPE_INT16},
	{"unknown3", TYPE_INT16},
	{"state_id", TYPE_INT32},
	{"state_level_base", TYPE_INT32},
	{"state_level_per_skl", TYPE_FLOAT32},
	{"state_level_per_enhance", TYPE_FLOAT32},
	{"state_second", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"state_second_per_level", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"state_second_per_enhance", TYPE_DECIMAL, MAKEINDEXEDVAR(2, 1)},
	{"state_type", TYPE_INT8},
	{"unknown4", TYPE_INT8},
	{"unknown5", TYPE_INT8},
	{"unknown6", TYPE_INT8},
	{"probability_on_hit", TYPE_INT32},
	{"probability_inc_by_slv", TYPE_INT32},
	{"hit_bonus", TYPE_INT16},
	{"hit_bonus_per_enhance", TYPE_INT16},
	{"percentage", TYPE_INT16},
	{"unknown7", TYPE_INT16},
	{"hate_mod", TYPE_FLOAT32},
	{"hate_basic", TYPE_INT32},
	{"hate_per_skl", TYPE_FLOAT32},
	{"hate_per_enhance", TYPE_FLOAT32},
	{"critical_bonus", TYPE_INT32},
	{"critical_bonus_per_skl", TYPE_INT32},
	{"var1", TYPE_FLOAT32},
	{"var2", TYPE_FLOAT32},
	{"var3", TYPE_FLOAT32},
	{"var4", TYPE_FLOAT32},
	{"var5", TYPE_FLOAT32},
	{"var6", TYPE_FLOAT32},
	{"var7", TYPE_FLOAT32},
	{"var8", TYPE_FLOAT32},
	{"var9", TYPE_FLOAT32},
	{"var10", TYPE_FLOAT32},
	{"var11", TYPE_FLOAT32},
	{"var12", TYPE_FLOAT32},
	{"var13", TYPE_FLOAT32},
	{"var14", TYPE_FLOAT32},
	{"var15", TYPE_FLOAT32},
	{"var16", TYPE_FLOAT32},
	{"var17", TYPE_FLOAT32},
	{"var18", TYPE_FLOAT32},
	{"var19", TYPE_FLOAT32},
	{"var20", TYPE_FLOAT32},
	{"jp_01", TYPE_INT32},
	{"jp_02", TYPE_INT32},
	{"jp_03", TYPE_INT32},
	{"jp_04", TYPE_INT32},
	{"jp_05", TYPE_INT32},
	{"jp_06", TYPE_INT32},
	{"jp_07", TYPE_INT32},
	{"jp_08", TYPE_INT32},
	{"jp_09", TYPE_INT32},
	{"jp_10", TYPE_INT32},
	{"jp_11", TYPE_INT32},
	{"jp_12", TYPE_INT32},
	{"jp_13", TYPE_INT32},
	{"jp_14", TYPE_INT32},
	{"jp_15", TYPE_INT32},
	{"jp_16", TYPE_INT32},
	{"jp_17", TYPE_INT32},
	{"jp_18", TYPE_INT32},
	{"jp_19", TYPE_INT32},
	{"jp_20", TYPE_INT32},
	{"jp_21", TYPE_INT32},
	{"jp_22", TYPE_INT32},
	{"jp_23", TYPE_INT32},
	{"jp_24", TYPE_INT32},
	{"jp_25", TYPE_INT32},
	{"jp_26", TYPE_INT32},
	{"jp_27", TYPE_INT32},
	{"jp_28", TYPE_INT32},
	{"jp_29", TYPE_INT32},
	{"jp_30", TYPE_INT32},
	{"jp_31", TYPE_INT32},
	{"jp_32", TYPE_INT32},
	{"jp_33", TYPE_INT32},
	{"jp_34", TYPE_INT32},
	{"jp_35", TYPE_INT32},
	{"jp_36", TYPE_INT32},
	{"jp_37", TYPE_INT32},
	{"jp_38", TYPE_INT32},
	{"jp_39", TYPE_INT32},
	{"jp_40", TYPE_INT32},
	{"jp_41", TYPE_INT32},
	{"jp_42", TYPE_INT32},
	{"jp_43", TYPE_INT32},
	{"jp_44", TYPE_INT32},
	{"jp_45", TYPE_INT32},
	{"jp_46", TYPE_INT32},
	{"jp_47", TYPE_INT32},
	{"jp_48", TYPE_INT32},
	{"jp_49", TYPE_INT32},
	{"jp_50", TYPE_INT32},
	{"unknown8", TYPE_INT32},
	{"tooltip_id", TYPE_INT32},
	{"icon_id", TYPE_INT32},
	{"icon_file_name", TYPE_CHAR, 256},
	{"is_projectile", TYPE_INT8},
	{"unknown8", TYPE_INT8},
	{"unknown9", TYPE_INT8},
	{"unknown10", TYPE_INT8},
	{"projectile_speed", TYPE_FLOAT32},
	{"projectile_acceleration", TYPE_FLOAT32},
}

rdb.sqlColumnOrder = table.concat({
	"id\0",
	"text_id\0",
	"desc_id\0",
	"tooltip_id\0",
	"is_valid\0",
	"elemental\0",
	"is_passive\0",
	"is_physical_act\0",
	"is_harmful\0",
	"is_need_target\0",
	"is_corpse\0",
	"is_toggle\0",
	"toggle_group\0",
	"casting_type\0",
	"casting_level\0",
	"cast_range\0",
	"valid_range\0",
	"cost_hp\0",
	"cost_hp_per_skl\0",
	"cost_mp\0",
	"cost_mp_per_skl\0",
	"cost_mp_per_enhance\0",
	"cost_hp_per\0",
	"cost_hp_per_skl_per\0",
	"cost_mp_per\0",
	"cost_mp_per_skl_per\0",
	"cost_havoc\0",
	"cost_havoc_per_skl\0",
	"cost_energy\0",
	"cost_energy_per_skl\0",
	"cost_exp\0",
	"cost_exp_per_enhance\0",
	"cost_jp\0",
	"cost_jp_per_enhance\0",
	"cost_item\0",
	"cost_item_count\0",
	"cost_item_count_per_skl\0",
	"need_level\0",
	"need_hp\0",
	"need_mp\0",
	"need_havoc\0",
	"need_havoc_burst\0",
	"need_state_id\0",
	"need_state_level\0",
	"need_state_exhaust\0",
	"vf_one_hand_sword\0",
	"vf_two_hand_sword\0",
	"vf_double_sword\0",
	"vf_dagger\0",
	"vf_double_dagger\0",
	"vf_spear\0",
	"vf_axe\0",
	"vf_one_hand_axe\0",
	"vf_double_axe\0",
	"vf_one_hand_mace\0",
	"vf_two_hand_mace\0",
	"vf_lightbow\0",
	"vf_heavybow\0",
	"vf_crossbow\0",
	"vf_one_hand_staff\0",
	"vf_two_hand_staff\0",
	"vf_shield_only\0",
	"vf_is_not_need_weapon\0",
	"delay_cast\0",
	"delay_cast_per_skl\0",
	"delay_cast_mode_per_enhance\0",
	"delay_common\0",
	"delay_cooltime\0",
	"delay_cooltime_mode_per_enhance\0",
	"cool_time_group_id\0",
	"uf_self\0",
	"uf_party\0",
	"uf_guild\0",
	"uf_neutral\0",
	"uf_purple\0",
	"uf_enemy\0",
	"tf_avatar\0",
	"tf_summon\0",
	"tf_monster\0",
	"target\0",
	"effect_type\0",
	"state_id\0",
	"state_level_base\0",
	"state_level_per_skl\0",
	"state_level_per_enhance\0",
	"state_second\0",
	"state_second_per_level\0",
	"state_second_per_enhance\0",
	"state_type\0",
	"probability_on_hit\0",
	"probability_inc_by_slv\0",
	"hit_bonus\0",
	"hit_bonus_per_enhance\0",
	"percentage\0",
	"hate_mod\0",
	"hate_basic\0",
	"hate_per_skl\0",
	"hate_per_enhance\0",
	"critical_bonus\0",
	"critical_bonus_per_skl\0",
	"var1\0",
	"var2\0",
	"var3\0",
	"var4\0",
	"var5\0",
	"var6\0",
	"var7\0",
	"var8\0",
	"var9\0",
	"var10\0",
	"var11\0",
	"var12\0",
	"var13\0",
	"var14\0",
	"var15\0",
	"var16\0",
	"var17\0",
	"var18\0",
	"var19\0",
	"var20\0",
	"jp_01\0",
	"jp_02\0",
	"jp_03\0",
	"jp_04\0",
	"jp_05\0",
	"jp_06\0",
	"jp_07\0",
	"jp_08\0",
	"jp_09\0",
	"jp_10\0",
	"jp_11\0",
	"jp_12\0",
	"jp_13\0",
	"jp_14\0",
	"jp_15\0",
	"jp_16\0",
	"jp_17\0",
	"jp_18\0",
	"jp_19\0",
	"jp_20\0",
	"jp_21\0",
	"jp_22\0",
	"jp_23\0",
	"jp_24\0",
	"jp_25\0",
	"jp_26\0",
	"jp_27\0",
	"jp_28\0",
	"jp_29\0",
	"jp_30\0",
	"jp_31\0",
	"jp_32\0",
	"jp_33\0",
	"jp_34\0",
	"jp_35\0",
	"jp_36\0",
	"jp_37\0",
	"jp_38\0",
	"jp_39\0",
	"jp_40\0",
	"jp_41\0",
	"jp_42\0",
	"jp_43\0",
	"jp_44\0",
	"jp_45\0",
	"jp_46\0",
	"jp_47\0",
	"jp_48\0",
	"jp_49\0",
	"jp_50\0",
	"icon_id\0",
	"icon_file_name\0",
	"is_projectile\0",
	"projectile_speed\0",
	"projectile_acceleration\0",
})

rdb.defaultTableName = "SkillFullResource"

rdb.convertData = function (dst, mode, row, rowNum)
	if mode == DCT_Read and dst == DF_RDB then
		row.desc_id = 0
	end
end

