rdb.fields = {
	{"state_id", TYPE_INT32},
	{"text_id", TYPE_INT32},
	{"tooltip_id", TYPE_INT32},
	{"is_harmful", TYPE_INT8},
	{"padding0", TYPE_INT8 | TYPE_SQLIGNORE},
	{"padding1", TYPE_INT16 | TYPE_SQLIGNORE},
	{"state_time_type", TYPE_INT32},
	{"state_group", TYPE_INT32},
	{"uf_avatar", TYPE_INT8},
	{"uf_summon", TYPE_INT8},
	{"uf_monster", TYPE_INT8},
	{"reiteration_count", TYPE_INT8},
	{"effect_type", TYPE_INT32},
	{"value_0", TYPE_FLOAT64},
	{"value_1", TYPE_FLOAT64},
	{"value_2", TYPE_FLOAT64},
	{"value_3", TYPE_FLOAT64},
	{"value_4", TYPE_FLOAT64},
	{"value_5", TYPE_FLOAT64},
	{"value_6", TYPE_FLOAT64},
	{"value_7", TYPE_FLOAT64},
	{"value_8", TYPE_FLOAT64},
	{"value_9", TYPE_FLOAT64},
	{"value_10", TYPE_FLOAT64},
	{"value_11", TYPE_FLOAT64},
	{"icon_id", TYPE_INT32},
	{"icon_file_name", TYPE_CHAR, 256},
	{"fx_id", TYPE_INT32},
	{"pos_id", TYPE_INT32},
	{"cast_fx_id", TYPE_INT32},
	{"cast_fx_pos_id", TYPE_INT32},
	{"cast_skill_id", TYPE_INT32},
	{"hit_fx_id", TYPE_INT32},
	{"hit_fx_pos_id", TYPE_INT32},
	{"special_output_timing_id", TYPE_INT32},
	{"special_output_fx_id", TYPE_INT32},
	{"special_output_fx_pos_id", TYPE_INT32},
	{"special_output_fx_delay", TYPE_INT32},
}

rdb.defaultFileName = "db_tenacity"

