rdb.fields = {
	{"state_id", TYPE_INT32},
	{"text_id", TYPE_INT32},
	{"tooltip_id", TYPE_INT32},
	{"is_harmful", TYPE_INT8},
	{"padding0", TYPE_INT8 | TYPE_SQLIGNORE},
	{"padding1", TYPE_INT16 | TYPE_SQLIGNORE},
	{"state_time_type", TYPE_INT32},
	{"state_group", TYPE_INT32},
	{"duplicate_group_1", TYPE_INT32},
	{"duplicate_group_2", TYPE_INT32},
	{"duplicate_group_3", TYPE_INT32},
	{"uf_avatar", TYPE_INT8},
	{"uf_summon", TYPE_INT8},
	{"uf_monster", TYPE_INT8},
	{"unknown0", TYPE_INT8 | TYPE_SQLIGNORE},
	{"reiteration_count", TYPE_INT8},
	{"unknown1", TYPE_INT8 | TYPE_SQLIGNORE},
	{"unknown2", TYPE_INT16 | TYPE_SQLIGNORE},
	{"base_effect_id", TYPE_INT32},
	{"fire_interval", TYPE_INT32},
	{"elemental_type", TYPE_INT32},
	{"amplify_base", TYPE_FLOAT32},
	{"amplify_per_skl", TYPE_FLOAT32},
	{"add_damage_base", TYPE_INT32},
	{"add_damage_per_skl", TYPE_INT32},
	{"effect_type", TYPE_INT32},
	{"unknown3", TYPE_INT32 | TYPE_SQLIGNORE},
	{"value_0", TYPE_FLOAT64},
	{"value_1", TYPE_FLOAT64},
	{"value_2", TYPE_FLOAT64},
	{"value_3", TYPE_FLOAT64},
	{"value_4", TYPE_FLOAT64},
	{"value_5", TYPE_FLOAT64},
	{"value_6", TYPE_FLOAT64},
	{"value_7", TYPE_FLOAT64},
	{"value_8", TYPE_FLOAT64},
	{"value_9", TYPE_FLOAT64},
	{"value_10", TYPE_FLOAT64},
	{"value_11", TYPE_FLOAT64},
	{"value_12", TYPE_FLOAT64},
	{"value_13", TYPE_FLOAT64},
	{"value_14", TYPE_FLOAT64},
	{"value_15", TYPE_FLOAT64},
	{"value_16", TYPE_FLOAT64},
	{"value_17", TYPE_FLOAT64},
	{"value_18", TYPE_FLOAT64},
	{"value_19", TYPE_FLOAT64},
	{"icon_id", TYPE_INT32},
	{"icon_file_name", TYPE_CHAR, 256},
	{"fx_id", TYPE_INT32},
	{"pos_id", TYPE_INT32},
	{"cast_fx_id", TYPE_INT32},
	{"cast_fx_pos_id", TYPE_INT32},
	{"cast_skill_id", TYPE_INT32},
	{"hit_fx_id", TYPE_INT32},
	{"hit_fx_pos_id", TYPE_INT32},
	{"special_output_timing_id", TYPE_INT32},
	{"special_output_fx_id", TYPE_INT32},
	{"special_output_fx_pos_id", TYPE_INT32},
	{"special_output_fx_delay", TYPE_INT32},
	{"state_fx_id", TYPE_INT32},
	{"state_fx_pos_id", TYPE_INT32},
}

rdb.sqlColumnOrder = table.concat({
	"state_id\0",
	"text_id\0",
	"tooltip_id\0",
	"is_harmful\0",
	"state_time_type\0",
	"state_group\0",
	"duplicate_group_1\0",
	"duplicate_group_2\0",
	"duplicate_group_3\0",
	"uf_avatar\0",
	"uf_summon\0",
	"uf_monster\0",
	"reiteration_count\0",
	"base_effect_id\0",
	"fire_interval\0",
	"elemental_type\0",
	"amplify_base\0",
	"amplify_per_skl\0",
	"add_damage_base\0",
	"add_damage_per_skl\0",
	"effect_type\0",
	"value_0\0",
	"value_1\0",
	"value_2\0",
	"value_3\0",
	"value_4\0",
	"value_5\0",
	"value_6\0",
	"value_7\0",
	"value_8\0",
	"value_9\0",
	"value_10\0",
	"value_11\0",
	"value_12\0",
	"value_13\0",
	"value_14\0",
	"value_15\0",
	"value_16\0",
	"value_17\0",
	"value_18\0",
	"value_19\0",
	"icon_id\0",
	"icon_file_name\0",
	"fx_id\0",
	"pos_id\0",
	"cast_skill_id\0",
	"cast_fx_id\0",
	"cast_fx_pos_id\0",
	"hit_fx_id\0",
	"hit_fx_pos_id\0",
	"special_output_timing_id\0",
	"special_output_fx_id\0",
	"special_output_fx_pos_id\0",
	"special_output_fx_delay\0",
	"state_fx_id\0",
	"state_fx_pos_id\0",
})

rdb.defaultFileName = "db_tenacity"

rdb.convertData = function (dst, mode, row, rowNum)
	if mode == DCT_Read and dst == DF_SQL then
		row.unknown0 = 0
		row.unknown1 = 0
		row.unknown2 = 163
		row.unknown3 = 0xFFFC74
	end
end
