rdb.fields = {
	{"id", TYPE_INT32},
	{"name_id", TYPE_INT32},
	{"tooltip_id", TYPE_INT32},
	{"status_id", TYPE_INT32},
	{"rate", TYPE_INT8},
	{"opt_type_0", TYPE_INT16},
	{"opt_type_1", TYPE_INT16},
	{"opt_type_2", TYPE_INT16},
	{"opt_type_3", TYPE_INT16},
	{"opt_type_4", TYPE_INT16},
	{"opt_type_5", TYPE_INT16},
	{"opt_type_6", TYPE_INT16},
	{"opt_type_7", TYPE_INT16},
	{"opt_var1_0", TYPE_FLOAT32},
	{"opt_var1_1", TYPE_FLOAT32},
	{"opt_var1_2", TYPE_FLOAT32},
	{"opt_var1_3", TYPE_FLOAT32},
	{"opt_var1_4", TYPE_FLOAT32},
	{"opt_var1_5", TYPE_FLOAT32},
	{"opt_var1_6", TYPE_FLOAT32},
	{"opt_var1_7", TYPE_FLOAT32},
	{"opt_var2_0", TYPE_FLOAT32},
	{"opt_var2_1", TYPE_FLOAT32},
	{"opt_var2_2", TYPE_FLOAT32},
	{"opt_var2_3", TYPE_FLOAT32},
	{"opt_var2_4", TYPE_FLOAT32},
	{"opt_var2_5", TYPE_FLOAT32},
	{"opt_var2_6", TYPE_FLOAT32},
	{"opt_var2_7", TYPE_FLOAT32},
	{"effect_id", TYPE_INT32},
	{"local_flag", TYPE_INT32},
	{"is_periodic", TYPE_INT8},
	{"begin_of_period", TYPE_INT32},
	{"end_of_period", TYPE_INT32},
}

rdb.defaultFileName = "db_titleresource"

