rdb.fields = {
	{"id", TYPE_INT32},
	{"text_id", TYPE_INT32},
	{"x", TYPE_INT32},
	{"y", TYPE_INT32},
	{"preloading_distance", TYPE_INT32},
	{"apply_location_name", TYPE_INT32},
	{"apply_light", TYPE_INT32},
	{"apply_bgm", TYPE_INT32},
	{"location_type", TYPE_INT32},
	{"fog_application", TYPE_INT32},
	{"time_id", TYPE_INT32},
	{"weather_id", TYPE_INT32},
	{"cloud_ratio", TYPE_INT32},
	{"weather_change_time", TYPE_INT32},
	{"weather_ratio", TYPE_INT32},
	{"sky_start_a", TYPE_INT32},
	{"sky_start_r", TYPE_INT32},
	{"sky_start_g", TYPE_INT32},
	{"sky_start_b", TYPE_INT32},
	{"sky_mid_a", TYPE_INT32},
	{"sky_mid_r", TYPE_INT32},
	{"sky_mid_g", TYPE_INT32},
	{"sky_mid_b", TYPE_INT32},
	{"sky_end_a", TYPE_INT32},
	{"sky_end_r", TYPE_INT32},
	{"sky_end_g", TYPE_INT32},
	{"sky_end_b", TYPE_INT32},
	{"sky_mid_rate", TYPE_FLOAT32},
	{"diffuse_a", TYPE_INT32},
	{"diffuse_r", TYPE_INT32},
	{"diffuse_g", TYPE_INT32},
	{"diffuse_b", TYPE_INT32},
	{"ambient_a", TYPE_INT32},
	{"ambient_r", TYPE_INT32},
	{"ambient_g", TYPE_INT32},
	{"ambient_b", TYPE_INT32},
	{"specular_a", TYPE_INT32},
	{"specular_r", TYPE_INT32},
	{"specular_g", TYPE_INT32},
	{"specular_b", TYPE_INT32},
	{"fog_a", TYPE_INT32},
	{"fog_r", TYPE_INT32},
	{"fog_g", TYPE_INT32},
	{"fog_b", TYPE_INT32},
	{"v_start", TYPE_FLOAT32},
	{"v_end", TYPE_FLOAT32},
	{"h_start", TYPE_FLOAT32},
	{"h_end", TYPE_FLOAT32},
	{"fixed_terrain_distance", TYPE_INT16},
	{"cloud_a", TYPE_INT32},
	{"cloud_r", TYPE_INT32},
	{"cloud_g", TYPE_INT32},
	{"cloud_b", TYPE_INT32},
	{"land_specular", TYPE_FLOAT32},
	{"character_diffuse", TYPE_FLOAT32},
	{"character_ambient", TYPE_FLOAT32},
	{"sun_texture_file", TYPE_CHAR, 256},
	{"moon_texture_file", TYPE_CHAR, 256},
	{"cloud_texture_file", TYPE_CHAR, 256},
	{"bgm1_ID", TYPE_INT32},
	{"bgm2_ID", TYPE_INT32},
	{"bgm3_ID", TYPE_INT32},
	{"bgm1_ratio", TYPE_INT32},
	{"bgm2_ratio", TYPE_INT32},
	{"bgm3_ratio", TYPE_INT32},
	{"environmental_sound1_ID", TYPE_INT32},
	{"environmental_sound2_ID", TYPE_INT32},
	{"environmental_sound3_ID", TYPE_INT32},
	{"environmental_sound4_ID", TYPE_INT32},
	{"environmental_sound1_ratio", TYPE_INT32},
	{"environmental_sound2_ratio", TYPE_INT32},
	{"environmental_sound3_ratio", TYPE_INT32},
	{"environmental_sound4_ratio", TYPE_INT32},
	{"environmental_sound_reverb", TYPE_INT32},
	{"environmental_sound_volume", TYPE_INT32},
	{"environmental_sound_equalizer", TYPE_INT32},
	{"minimap_ani_file_ID", TYPE_INT16},
	{"worldmap_ani_file_ID", TYPE_INT16},
	{"unknownvalue0", TYPE_INT8 | TYPE_SQLIGNORE | TYPE_CSVIGNORE},
	{"zoom_map_type", TYPE_INT32},
	{"display_positoin_x", TYPE_INT32},
	{"display_positoin_y", TYPE_INT32},
	{"zoom_x", TYPE_INT32},
	{"offset_x", TYPE_INT32},
	{"offset_y", TYPE_INT32},
	{"size_x", TYPE_INT32},
	{"size_y", TYPE_INT32},
	{"blank_resource_ID", TYPE_INT32},
	{"blank_a", TYPE_INT32},
	{"blank_r", TYPE_INT32},
	{"blank_g", TYPE_INT32},
	{"blank_b", TYPE_INT32},
	{"zoom_minimap", TYPE_INT32},
	{"precipitation_min", TYPE_INT32},
	{"precipitation_max", TYPE_INT32},
	{"aurora_t", TYPE_FLOAT32},
	{"aurora_a", TYPE_FLOAT32},
	{"aurora_s", TYPE_FLOAT32},
	{"aurora_h", TYPE_FLOAT32},
}

rdb.sqlColumnOrder = table.concat({
	"id\0",
	"text_id\0",
	"x\0",
	"y\0",
	"preloading_distance\0",
	"apply_location_name\0",
	"apply_light\0",
	"apply_bgm\0",
	"location_type\0",
	"fog_application\0",
	"time_id\0",
	"weather_id\0",
	"cloud_ratio\0",
	"weather_change_time\0",
	"weather_ratio\0",
	"sky_start_a\0",
	"sky_start_r\0",
	"sky_start_g\0",
	"sky_start_b\0",
	"sky_mid_a\0",
	"sky_mid_r\0",
	"sky_mid_g\0",
	"sky_mid_b\0",
	"sky_end_a\0",
	"sky_end_r\0",
	"sky_end_g\0",
	"sky_end_b\0",
	"sky_mid_rate\0",
	"diffuse_a\0",
	"diffuse_r\0",
	"diffuse_g\0",
	"diffuse_b\0",
	"ambient_a\0",
	"ambient_r\0",
	"ambient_g\0",
	"ambient_b\0",
	"specular_a\0",
	"specular_r\0",
	"specular_g\0",
	"specular_b\0",
	"fog_a\0",
	"fog_r\0",
	"fog_g\0",
	"fog_b\0",
	"v_start\0",
	"v_end\0",
	"h_start\0",
	"h_end\0",
	"fixed_terrain_distance\0",
	"cloud_a\0",
	"cloud_r\0",
	"cloud_g\0",
	"cloud_b\0",
	"land_specular\0",
	"character_diffuse\0",
	"character_ambient\0",
	"sun_texture_file\0",
	"moon_texture_file\0",
	"cloud_texture_file\0",
	"bgm1_ID\0",
	"bgm1_ratio\0",
	"bgm2_ID\0",
	"bgm2_ratio\0",
	"bgm3_ID\0",
	"bgm3_ratio\0",
	"environmental_sound1_ID\0",
	"environmental_sound1_ratio\0",
	"environmental_sound2_ID\0",
	"environmental_sound2_ratio\0",
	"environmental_sound3_ID\0",
	"environmental_sound3_ratio\0",
	"environmental_sound4_ID\0",
	"environmental_sound4_ratio\0",
	"environmental_sound_reverb\0",
	"environmental_sound_volume\0",
	"environmental_sound_equalizer\0",
	"minimap_ani_file_ID\0",
	"worldmap_ani_file_ID\0",
	"zoom_map_type\0",
	"display_positoin_x\0",
	"display_positoin_y\0",
	"zoom_x\0",
	"offset_x\0",
	"offset_y\0",
	"size_x\0",
	"size_y\0",
	"blank_resource_ID\0",
	"blank_a\0",
	"blank_r\0",
	"blank_g\0",
	"blank_b\0",
	"zoom_minimap\0",
	"precipitation_min\0",
	"precipitation_max\0",
	"aurora_t\0",
	"aurora_a\0",
	"aurora_s\0",
	"aurora_h\0",
})

rdb.defaultTableName = "WorldLocation"

rdb.convertData = function (dst, mode, row, rowNum)
	if mode == DCT_Read and dst ~= DF_RDB then
		row.unknownvalue0 = 0
	end
end
